# Generated by Django 3.1.5 on 2021-01-29 12:07

import apps.client.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('project', 'Project'), ('engineering', 'Engineering'), ('puchasing', 'Puchasing'), ('accounting', 'Accounting'), ('other', 'Other')], default='project', max_length=20, verbose_name='Department')),
                ('name', models.CharField(max_length=30, verbose_name='Username')),
                ('contact', models.CharField(blank=True, max_length=12, validators=[apps.client.validators.validate_contact], verbose_name='Contact')),
                ('email', models.EmailField(blank=True, max_length=30, verbose_name='Email')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='uuid')),
                ('publish', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Clients', to='company.company')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'db_table': 'client',
                'ordering': ['name', 'uuid'],
                'permissions': [('publish_client', 'Can publish client')],
                'default_related_name': 'Clients',
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['name', 'uuid', 'department', 'company'], name='client_name_d7a54f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('name', 'uuid')},
        ),
    ]
