# Generated by Django 3.1.5 on 2021-01-29 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Code')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('open', 'Open'), ('close', 'Close')], default='open', max_length=15, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Projects', to='client.client', verbose_name='Client')),
                ('worker', models.ManyToManyField(related_name='Projects', to=settings.AUTH_USER_MODEL, verbose_name='Workers')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'db_table': 'project',
                'ordering': ['client', 'name', 'uuid'],
                'permissions': [('close_poject', 'Can close project')],
                'default_related_name': 'Projects',
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['client', 'name', 'uuid'], name='project_client__57b4c5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name', 'uuid')},
        ),
    ]
